version: '3.8'
services:
  whatsapp-mcp:
    build: .
    restart: unless-stopped
    ports:
      - "45679:45679"
    environment:
      - PORT=45679
      - NODE_ENV=production
      - WHATSAPP_API_VERSION=v18.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:45679/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Remove env_file reference - environment variables should be set in Coolify
    # env_file:
    #   - .env 